data:
  id: dlwh/wikitext_103_detokenized
model:
  type: gpt2
  hidden_dim: 8
  num_heads: 2
  num_layers: 2
trainer:
  tracker:
    project: "levanter"
    tags: [ "openwebtext", "gpt2"]

  mp: p=f32,c=bfloat16
  num_train_steps: 100
  per_device_eval_parallelism: 1
  train_batch_size: 2
l2_weight_decay_weight: 0.5
